tool.acfarmormesh.sphere_search_radius_desc=If set to a non zero value, the contraption readout will consider all entities within a sphere with this radius where you are looking.
tool.acfarmormesh.sphere_search_radius=Sphere search radius

tool.acfarmormesh.material_desc=Different material types have different densities, resistances to certain shell types and health characteristics.