-- Variables that should be persisted between server restarts

-- Settings
ACF.PersistServerData("LegalChecks", true)
ACF.PersistServerData("NameAndShame", false)
ACF.PersistServerData("VehicleLegalChecks", true)
ACF.PersistServerData("ServerDataAllowAdmin", false)
ACF.PersistServerData("RestrictInfo", true)
ACF.PersistServerData("GunsCanFire", true)
ACF.PersistServerData("GunsCanSmoke", true)
ACF.PersistServerData("RacksCanFire", true)
ACF.PersistServerData("RequireFuel", true)
ACF.PersistServerData("HealthFactor", 1)
ACF.PersistServerData("ArmorFactor", 1)
ACF.PersistServerData("FuelFactor", 1)
ACF.PersistServerData("MaxThickness", ACF.MaximumArmor)
ACF.PersistServerData("HEPush", true)
ACF.PersistServerData("KEPush", true)
ACF.PersistServerData("RecoilPush", true)
ACF.PersistServerData("Volume", 1)
ACF.PersistServerData("AllowFunEnts", true)
ACF.PersistServerData("AllowProcArmor", false)
ACF.PersistServerData("ShowFunMenu", true)
ACF.PersistServerData("WorkshopContent", true)
ACF.PersistServerData("WorkshopExtras", false)

-- Debris
ACF.PersistServerData("CreateDebris", true)
ACF.PersistServerData("CreateFireballs", false)
ACF.PersistServerData("FireballMult", 1)