local ACF      		= ACF

--- Configures a lua seat generated by the crew entity
--- Called when first creating the seat, or when reusing it from a dupe
function ENT:ConfigureLuaSeat(Pod, Player)
	ACF.ConfigureLuaSeat(self, Pod, Player)
	self:ACF_SetUserVar("AlreadyHasSeat", true)

	self.Pod = Pod

	hook.Add("PlayerEnteredVehicle", "ACFBaseplateSeatEnter" .. self:EntIndex(), function(Ply, Veh)
		if Veh == Pod then
			-- Ply:GodEnable() -- Remove this if aliases are removed?
			Ply:SetNoDraw(true)
		end
	end)

	-- Make the player visible and vulnerable when they leave the seat
	hook.Add("PlayerLeaveVehicle", "ACFBaseplateSeatExit" .. self:EntIndex(), function(Ply, Veh)
		if Veh == Pod then
			-- Ply:GodDisable() -- Remove this if aliases are removed?
			Ply:SetNoDraw(false)
		end
	end)

	-- Allow players to enter the seat externally by pressing use on a prop on the same contraption as the baseplate
	hook.Add("PlayerUse", "ACFBaseplateSeatEnterExternal" .. self:EntIndex(), function(Ply, Ent)
		if not Ply:KeyDown(IN_WALK) then return end
		if IsValid(Ent) then
			local Contraption = Ent:GetContraption()
			if Contraption then
				local Base = Contraption.ACF_Baseplate
				if Base == self and IsValid(Pod) and Pod:GetDriver() ~= Ply and not self:ACF_GetUserVar("DisableAltE") then
					Ply:EnterVehicle(Pod)
				end
			end
		end
	end)

	-- Cleanup hooks and stuff when the baseplate is removed
	self:CallOnRemove("ACF_RemoveVehiclePod", function(Ent)
		hook.Remove("PlayerEnteredVehicle", "ACFBaseplateSeatEnter" .. self:EntIndex())
		hook.Remove("PlayerLeaveVehicle", "ACFBaseplateSeatExit" .. self:EntIndex())
		hook.Remove("PlayerUse", "ACFBaseplateSeatEnterExternal" .. self:EntIndex())

		--local Owner = self:CPPIGetOwner()
		--if IsValid(Owner) then Owner:GodDisable() end

		SafeRemoveEntity(Ent.Pod)

		if self.Crews and next(self.Crews) then
			for Crew in pairs(self.Crews) do
				if IsValid(Crew) then self:Unlink(Crew) end
			end
		end
	end)

	WireLib.TriggerOutput(self, "Vehicles", {Pod})
end

-- Exposes Pod to util_sh and other things with a more unique name
-- frankly, should rename Pod entirely
function ENT:ACF_GetSeatProxy() return self.Pod end