name: GLuaLint

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**'
  pull_request:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**'

jobs:
  Lint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    with:
      config: "./.glualint.json"